### ISSUE TITLE
socket hung up error on large messages

### ISSUE THREAD

**Issue by Charuru** [SocketCluster/socketcluster#240]
I never had this problem before, only appearing after i upgraded from 4.x to 5.0.18.

I'm transferring a large message which fails with socket hung up 1006.

Even dividing up the message into small messages does not work, so long as i try to send them all at once I get the same issue. The problem exists only with my dev osx computer and works fine on my server running ubuntu.

Socketcluster shows

`Got error: connect ECONNREFUSED 127.0.0.1:80`

And my app shows:

```
Socket error - SocketProtocolError: Socket hung up
socketCluster CONNECTED
Socket error - SocketProtocolError: Socket hung up
socketCluster CONNECTED
Socket error - SocketProtocolError: Socket hung up
socketCluster CONNECTED
```

Maybe it's a thing in uws?

Edit: Another difference is that the server is running https while the localhost is unsecured.

**Comment by jondubois** [comment]
I just tested on OSX (SC v5.0.18) with both ws and uws and couldn't reproduce the issue. Do you have a proxy (I.e. a firewall) running on your localhost which might be blocking WS connections? If serving over HTTPS fixes the issue, then there is a chance that it's a proxy issue.

**Comment by jondubois** [comment]
@Charuru

**Comment by jondubois** [comment]
@Charuru I was able to reproduce this on React Native when using the ws module on the backend. I fixed it with socketcluster-client `v5.0.18`.

**Comment by zalmoxisus** [comment]
@jondubois it doesn't affect `uws` which is by default? Can it be related with https://github.com/jhen0409/remote-redux-devtools-on-debugger/issues/15 and https://github.com/zalmoxisus/remote-redux-devtools/issues/50? The messages are also getting large there and the server is also on https as in the issue.

**Comment by jondubois** [comment]
@zalmoxisus Based on the latest RN version, this specific fix only affected ws. Yes uws is the default... But this fix could be relevant for older RN versions maybe?

I haven't noticed any issue with uws and large message sizes but if you can give me some sample messages with which I can reproduce the issue, I'd be happy to test and fix it.

I tried sending a large object with 100K randomly generated keys and didn't have any issues.

**Comment by zalmoxisus** [comment]
@jondubois, I wish I could reproduce and have more details, but it also works well for me, though I'm not running it much on React Native.

**Comment by Charuru** [comment]
Updating the client didn't fix it for me. I was using uws. I'll try to get you an example of a message, I think it might've been larger than 100k.

**Comment by Charuru** [comment]
Yeah it was a 1.7m log file.

https://gist.github.com/Charuru/ab35171707c62405683b2fa3154663e5

**Comment by jondubois** [comment]
@Charuru Yes that is a big file - I'll test later. I'll check with Alex (author of uWS) to see if he can think of something.

So you're saying that this only happens with uws (not ws) and that even if you break it up into smaller pieces but send them all at once, it causes the socket to hang up? Do you get any server-side errors?

**Comment by jondubois** [comment]
@Charuru I tested with the 1.7m log file and it was no problem. It took a fraction of a second to send and receive the entire thing on my machine. The issue only happens on your localhost? So it's not going over the network?

**Comment by Charuru** [comment]
I'm going to try with ws.

Serverside error I got is: `Got error: connect ECONNREFUSED 127.0.0.1:80`

**Comment by Charuru** [comment]
Yep works fine with ws.

I think I'm going to go back to ws for development for now. It's only on localhost, no firewall.

**Comment by jondubois** [comment]
@Charuru Can you post a series of exact steps which I can follow (and code I can copy/paste) to reproduce the issue on my machine?

I'd like to understand what happened in case anyone else runs into the same problem in the future.

Also, one more thing you can try to get it to work with uws is checking that you have the latest `uws` version as a dependency. It should be `v0.11.0` or higher - Sometimes npm can keep old dependencies in cache when you upgrade modules.

**Comment by alexhultman** [comment]
The only limit that can come into play is the 16mb limit per message (this is hardcoded currently), but that is only for receives. Is this 1.7mb file inflated to something larger than 16mb by any kind of base64 or something similar?

**Comment by happilymarrieddad** [comment]
@alexhultman is it possible to make that 16mb limit a parameter somewhere?
